# Generated by Django 4.2.7 on 2023-11-27 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_remove_song_lyrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
